mainConfig:
  appName: your app name
  host: 0.0.0.0
  port: 8000
  workerId: 1
mysqlConfig:
  host: 127.0.0.1
  port: 3307
  user: windows
  password: 123456
  databaseName: doovvvdp
  maxIdleConns: 10
  maxOpenConns: 100
  connMaxLifetime: 300

redisConfig:
  host: 127.0.0.1
  port: 6380 
  password: ""
  db: 0

logConfig:
  path: ./test.log
kafkaConfig:
  messageMode: "channel" #消息模式 channel or kafka
  hostPort: "127.0.0.1:9092" # "127.0.0.1:9092,127.0.0.1:9093,127.0.0.1:9094" 多个kafka服务器
  orderTopic: "voucher-orders"
  partition: 0 # kafka partition
  timeout: 1 # 单位秒